/* ═══════════════════════════════════════════════════════════════
   ARCHIVE.99 — pixel icon factory
   Icons are drawn as 16×16 ASCII pixel maps and compiled to SVG
   data-URIs at load. Palette keys:
     . transparent   k jet black   w white        c cloud dancer
     n nimbus        d dark grey   b estate blue  h light blue
     r flame scarlet y manila      o dark manila  g green

   Plain script (no ES modules) — works even when index.html is
   opened directly from disk (file://), not just via a web server.
   Everything hangs off the shared window.A99 namespace.
   ═══════════════════════════════════════════════════════════════ */

window.A99 = window.A99 || {};

(function () {
  const PAL = {
    k: "#2B2B2D", w: "#FFFFFF", c: "#F0EEE4", n: "#D4D4D6",
    d: "#7A7A80", b: "#233A5E", h: "#5B7DB1", r: "#CD212A",
    y: "#E8D9A0", o: "#B09A55", g: "#4E7A4E",
  };

  function toSvg(rows) {
    const h = rows.length, w = rows[0].length;
    let rects = "";
    for (let y = 0; y < h; y++) {
      let x = 0;
      while (x < w) {
        const ch = rows[y][x];
        if (ch === "." || !PAL[ch]) { x++; continue; }
        let run = 1;
        while (x + run < w && rows[y][x + run] === ch) run++;
        rects += `<rect x="${x}" y="${y}" width="${run}" height="1" fill="${PAL[ch]}"/>`;
        x += run;
      }
    }
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}" shape-rendering="crispEdges">${rects}</svg>`;
    return "data:image/svg+xml," + encodeURIComponent(svg);
  }

  const MAPS = {
    folder: [
      "................",
      "................",
      ".kkkkkk.........",
      "kyyyyyyk........",
      "kyyyyyykkkkkkkk.",
      "kyyyyyyyyyyyyyk.",
      "kyoooooooooooyk.",
      "kyoyyyyyyyyyoyk.",
      "kyoyyyyyyyyyoyk.",
      "kyoyyyyyyyyyoyk.",
      "kyoyyyyyyyyyoyk.",
      "kyoyyyyyyyyyoyk.",
      "kyoooooooooooyk.",
      "kyyyyyyyyyyyyyk.",
      ".kkkkkkkkkkkkk..",
      "................",
    ],
    casefolder: [
      "................",
      "................",
      ".kkkkkk.........",
      "kyyyyyyk........",
      "kyyyyyykkkkkkkk.",
      "kyyyyyyyyyyyyyk.",
      "kyrrrrryyyyyyyk.",
      "kyrwwwryyyyyyyk.",
      "kyrrrrryyyyyyyk.",
      "kyyyyyyyyyyyyyk.",
      "kyyykkkkkkkyyyk.",
      "kyyyyyyyyyyyyyk.",
      "kyyykkkkkyyyyyk.",
      "kyyyyyyyyyyyyyk.",
      ".kkkkkkkkkkkkk..",
      "................",
    ],
    document: [
      "................",
      "..kkkkkkkkk.....",
      "..kwwwwwwwkk....",
      "..kwwwwwwwkwk...",
      "..kwwwwwwwkkkk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbwwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbbwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbwwwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbbwwk..",
      "..kwwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    pdf: [
      "................",
      "..kkkkkkkkk.....",
      "..kwwwwwwwkk....",
      "..kwwwwwwwkwk...",
      "..kwwwwwwwkkkk..",
      "..kwwwwwwwwwwk..",
      "..kwrrrwwwwwwk..",
      "..kwrwrwrrwrwk..",
      "..kwrrrwrwwrwk..",
      "..kwrwwwrwwrwk..",
      "..kwrwwwrrwrwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbwwwk..",
      "..kwwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
    ],
    notepad: [
      "................",
      "..kkkkkkkkkkkk..",
      "..knnnnnnnnnnk..",
      "..kkkkkkkkkkkk..",
      "..kwwwwwwwwwwk..",
      "..kwkwkwkwkwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbbwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbwwwwk..",
      "..kwwwwwwwwwwk..",
      "..kwbbbbbbwwwk..",
      "..kwwwwwwwwwwk..",
      "..kwwwwwwwkkk...",
      "..kkkkkkkkk.....",
      "................",
    ],
    phone: [
      "................",
      "................",
      "....kkkkkkkk....",
      "...kddddddddk...",
      "..kddkkkkkkddk..",
      ".kdk........kdk.",
      ".kk..........kk.",
      "................",
      "....kkkkkkkk....",
      "...kddddddddk...",
      "..kdnnnnnnnndk..",
      "..kdnwwnwwnndk..",
      "..kdnwwnwwnndk..",
      "..kdnnnnnnnndk..",
      "..kddddddddddk..",
      "..kkkkkkkkkkkk..",
    ],
    recycle: [
      "................",
      "....kkkkkkkk....",
      "...kwnnnnnnwk...",
      "..kwnkkkkkknwk..",
      "..kkkkkkkkkkkk..",
      "...knnnnnnnnk...",
      "...knkgkgknk....",
      "...knkgkgkgnk...",
      "...knkgkgkgnk...",
      "...knkgkgkgnk...",
      "...knkgkgkgnk...",
      "...knkgkgkgnk...",
      "...knnnnnnnnk...",
      "....kkkkkkkk....",
      "................",
      "................",
    ],
    film: [
      "................",
      ".kkkkkkkkkkkkkk.",
      ".kwkbbbbbbbkwkk.",
      ".kkkbbbbbbbkkkk.",
      ".kwkbhhhhbbkwkk.",
      ".kkkbhbbhbbkkkk.",
      ".kwkbbbbbbbkwkk.",
      ".kkkkkkkkkkkkkk.",
      ".kwkbbbbbbbkwkk.",
      ".kkkbbhhbbbkkkk.",
      ".kwkbhbbhbbkwkk.",
      ".kkkbbbbbbbkkkk.",
      ".kwkbbbbbbbkwkk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
    camera: [
      "................",
      "................",
      "...kkkk.........",
      "..kddddk........",
      ".kkkkkkkkkkkkkk.",
      ".kddddddddddddk.",
      ".kddkkkkkddddgk.",
      ".kdkwnnnnkddddk.",
      ".kdkwnbbnkddddk.",
      ".kdkwnbbnkddddk.",
      ".kdkwnnnnkddddk.",
      ".kddkkkkkddddkk.",
      ".kddddddddddddk.",
      ".kkkkkkkkkkkkkk.",
      "................",
      "................",
    ],
    pen: [
      "................",
      "...........kk..",
      "..........krrk.",
      ".........krrrk.",
      "........krrrk..",
      ".......kwwrk...",
      "......kwwwk....",
      ".....kwwwk.....",
      "....kwwwk......",
      "...kwwwk.......",
      "...kwwk........",
      "..kkwk.........",
      "..kkk..........",
      "..kk...........",
      "................",
      "................",
    ],
    computer: [
      "................",
      ".kkkkkkkkkkkkk..",
      ".knnnnnnnnnnnk..",
      ".knbbbbbbbbbnk..",
      ".knbwbbbbbbbnk..",
      ".knbbbbbbbbbnk..",
      ".knbbbbbbbbbnk..",
      ".knbbbbbbbbbnk..",
      ".knnnnnnnnnnnk..",
      ".kkkkkkkkkkkkk..",
      "....kknnkk......",
      "...kknnnnkk.....",
      ".kkkkkkkkkkkk...",
      ".knnnnnnnnnnk...",
      ".kkkkkkkkkkkk...",
      "................",
    ],
    mines: [
      "................",
      "................",
      ".......k........",
      "...k...k...k....",
      "....k.kkk.k.....",
      ".....kkkkk......",
      "..kk.kkwkk.kk...",
      ".....kkkkkkk....",
      "....k.kkkkk.....",
      "...k...k...k....",
      ".......k........",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    run: [
      "................",
      "................",
      "..kkkkkkkkkkkk..",
      "..kwwwwwwwwwwk..",
      "..kwkwwwwwwwwk..",
      "..kwkkwwwwwwwk..",
      "..kwkkkwwwwwwk..",
      "..kwkkwwwwwwwk..",
      "..kwkwwkkkkwwk..",
      "..kwwwwwwwwwwk..",
      "..kkkkkkkkkkkk..",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
    help: [
      "................",
      "....kkkkkkkk....",
      "...kbbbbbbbbk...",
      "..kbbbwwwwbbbk..",
      "..kbbwwbbwwbbk..",
      "..kbbwwbbwwbbk..",
      "..kbbbbbwwbbbk..",
      "..kbbbbwwbbbbk..",
      "..kbbbwwbbbbbk..",
      "..kbbbwwbbbbbk..",
      "..kbbbbbbbbbbk..",
      "..kbbbwwbbbbbk..",
      "...kbbwwbbbbk...",
      "....kkkkkkkk....",
      "................",
      "................",
    ],
    cat: [
      "................",
      "................",
      "..k.....k.......",
      "..kk...kk.......",
      "..kkk.kkk.......",
      "..kkkkkkk.......",
      "..krkkkrk.......",
      "..kkkwkkk.......",
      "...kkkkk........",
      "....kkk.........",
      "...kkkkk........",
      "..kkkkkkk.......",
      "..kkkkkkk..kk...",
      "..kkkkkkkkkk....",
      "...kk..kk.......",
      "................",
    ],
    shutdown: [
      "................",
      "................",
      ".......kk.......",
      ".......kk.......",
      "....k..kk..k....",
      "...k...kk...k...",
      "..k....kk....k..",
      "..k....kk....k..",
      "..k..........k..",
      "..k..........k..",
      "...k........k...",
      "....k......k....",
      "......kkkk......",
      "................",
      "................",
      "................",
    ],
  };

  A99.ICONS = Object.fromEntries(
    Object.entries(MAPS).map(([name, rows]) => [name, toSvg(rows)])
  );

  /* favicon uses the case folder */
  A99.installFavicon = function installFavicon() {
    const link = document.querySelector("link[rel=icon]");
    if (link) link.href = A99.ICONS.casefolder;
  };
})();
